_schema-version: '3.1'
ID: cdsbuildtriggeredissue
version: 1.0.0
description: A simple CAP project.
parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
build-parameters:
  before-all:
    - builder: custom
      commands:
        - rm -rf build/dist
        - mkdir -p build/dist
        - rm -rf build/ui-deployer
        - mkdir -p build/ui-deployer
    - builder: custom
      commands:
        - npm install --production
        - >-
          bash -c "cds -v | grep 'cds-dk' || npm i --production --no-save
          @sap/cds-dk @sap/mdk-tools"
        - bash -c "export PATH=$PATH:$(pwd)/node_modules/.bin"
        - cds build --production
  after-all:
    - builder: custom
      commands:
        - npm install
modules:
  - name: cdsbuildtriggeredissue-cdsbuildtriggeredissue.mfeapplication
    type: html5
    path: app/cdsbuildtriggeredissue.mfeapplication
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/cdsbuildtriggeredissuemfeapplication.zip *"
      _artifactName: cdsbuildtriggeredissuemfeapplication.zip
      supported-platforms: []
      build-result: dist-zip
  - name: cdsbuildtriggeredissue-mymdkapplication
    type: html5
    path: app/mymdkapplication
    build-parameters:
      builder: custom
      commands:
        - npx mdk build --target module --ui5 --forceUpdate
        - bash -c "cd Web/MDKModule && rm -rf .npmrc && npm install"
        - bash -c "cd Web/MDKModule && npm run build"
        - >-
          bash -c "mv Web/MDKModule/MDKModule-content.zip
          ../../build/dist/mymdkapplication.zip"
        - rm -rf Web/MDKModule/dist
      _artifactName: mymdkapplication.zip
      supported-platforms: []
      build-result: ../../build/dist
  - name: cdsbuildtriggeredissue-db-deployer
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: cdsbuildtriggeredissue-service-uaa
      - name: cdsbuildtriggeredissue-service-db
  - name: cdsbuildtriggeredissue-srv
    type: nodejs
    path: gen/srv
    parameters:
      memory: 256MB
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: cdsbuildtriggeredissue-service-uaa
      - name: cdsbuildtriggeredissue-service-db
      - name: cdsbuildtriggeredissue-service-destination
      - name: cdsbuildtriggeredissue-service-metadata
      - name: cdsbuildtriggeredissue-service-connectivity
      - name: cdsbuildtriggeredissue-service-logs
  - name: cdsbuildtriggeredissue-aux-destinations
    type: com.sap.application.content
    parameters:
      content:
        subaccount:
          existing_destinations_policy: update
          destinations:
            - Authentication: OAuth2UserTokenExchange
              Name: cdsbuildtriggeredissue-service-uaa
              ServiceInstanceName: cdsbuildtriggeredissue-uaa
              ServiceKeyName: cdsbuildtriggeredissue-uaa-key
              sap.cloud.service: lcap.cdsbuildtriggeredissue
            - Authentication: OAuth2UserTokenExchange
              Name: cdsbuildtriggeredissue-app-srv
              TokenServiceInstanceName: cdsbuildtriggeredissue-uaa
              TokenServiceKeyName: cdsbuildtriggeredissue-uaa-key
              URL: ~{srv-api/srv-url}
              sap.cloud.service: lcap.cdsbuildtriggeredissue
            - Name: cdsbuildtriggeredissue-service-html5-apps-repo-host
              ServiceInstanceName: cdsbuildtriggeredissue-html5-apps-repo-host
              ServiceKeyName: cdsbuildtriggeredissue-html5-apps-repo-host-key
              sap.cloud.service: lcap.cdsbuildtriggeredissue
            - Authentication: OAuth2UserTokenExchange
              Name: cdsbuildtriggeredissue-cdsbuildtriggeredissueService
              TokenServiceInstanceName: cdsbuildtriggeredissue-uaa
              TokenServiceKeyName: cdsbuildtriggeredissue-uaa-key
              URL: ~{srv-api/srv-url}/service/cdsbuildtriggeredissueService
              sap.cloud.service: lcap.cdsbuildtriggeredissue
              sap.applicationdevelopment.actions.enabled: false
              sap.build.usage: CAP
              sap.processautomation.enabled: false
              HTML5.DynamicDestination: false
              WebIDEEnabled: false
              MobileEnabled: false
              AppgyverEnabled: false
    build-parameters:
      no-source: true
    requires:
      - name: cdsbuildtriggeredissue-service-uaa
        parameters:
          service-key:
            name: cdsbuildtriggeredissue-uaa-key
      - name: srv-api
      - name: cdsbuildtriggeredissue-service-html5-apps-repo-host
        parameters:
          service-key:
            name: cdsbuildtriggeredissue-html5-apps-repo-host-key
      - name: cdsbuildtriggeredissue-service-destination
        parameters:
          content-target: true
  - name: cdsbuildtriggeredissue-launchpad
    type: html5
    path: build/launchpad
    build-parameters:
      builder: custom
      commands:
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - bash -c "cd dist && npx bestzip ../../../build/dist/launchpad.zip *"
        - rm -rf dist
      _artifactName: launchpad.zip
      supported-platforms: []
      build-result: ../../build/dist
  - name: cdsbuildtriggeredissue-aux-ui-deployer
    type: com.sap.application.content
    path: build/ui-deployer
    build-parameters:
      build-result: resources
      requires:
        - name: cdsbuildtriggeredissue-cdsbuildtriggeredissue.mfeapplication
          artifacts:
            - cdsbuildtriggeredissuemfeapplication.zip
          target-path: resources
        - name: cdsbuildtriggeredissue-mymdkapplication
          artifacts:
            - mymdkapplication.zip
          target-path: resources
        - name: cdsbuildtriggeredissue-launchpad
          artifacts:
            - launchpad.zip
          target-path: resources
    requires:
      - name: cdsbuildtriggeredissue-service-html5-apps-repo-host
        parameters:
          content-target: true
resources:
  - type: org.cloudfoundry.managed-service
    name: cdsbuildtriggeredissue-service-uaa
    parameters:
      service: xsuaa
      service-plan: application
      service-name: cdsbuildtriggeredissue-uaa
      path: xs-security.json
      config:
        oauth2-configuration:
          redirect-uris:
            - https://*.${default-domain}/login/*
          credential-types:
            - binding-secret
            - x509
        xsappname: cdsbuildtriggeredissue-${space}
        role-collections: []
  - type: org.cloudfoundry.managed-service
    name: cdsbuildtriggeredissue-service-db
    parameters:
      service: hana
      service-plan: hdi-shared
      service-name: cdsbuildtriggeredissue-db
  - type: org.cloudfoundry.managed-service
    name: cdsbuildtriggeredissue-service-destination
    parameters:
      service: destination
      service-plan: lite
      service-name: cdsbuildtriggeredissue-destination
      config:
        HTML5Runtime_enabled: true
        version: 1.0.0
  - type: org.cloudfoundry.user-provided-service
    name: cdsbuildtriggeredissue-service-metadata
    parameters:
      service: metadata
      service-plan: standard
      service-name: cdsbuildtriggeredissue-metadata
      config:
        default-domain: ${default-domain}
  - type: org.cloudfoundry.managed-service
    name: cdsbuildtriggeredissue-service-connectivity
    parameters:
      service: connectivity
      service-plan: lite
      service-name: cdsbuildtriggeredissue-connectivity
  - type: org.cloudfoundry.managed-service
    name: cdsbuildtriggeredissue-service-logs
    parameters:
      service: application-logs
      service-plan: lite
      service-name: cdsbuildtriggeredissue-logs
  - type: org.cloudfoundry.managed-service
    name: cdsbuildtriggeredissue-service-html5-apps-repo-host
    parameters:
      service: html5-apps-repo
      service-plan: app-host
      service-name: cdsbuildtriggeredissue-html5-apps-repo-host
